### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by 1buran** [AndrewBurdyug/makechat#1]
Need a simple admin dashboard with such functionality:
- [ ] manage chat rooms(CRUD operations) 
- [ ] manage members of chat rooms(CRUD operations)
- [ ] manage users(CRUD operations, blocking)
- [ ] manage tokens(CRUD operations)
